export const HEADER_BACKGROUND = '#FFF';
export const PAGE_BACKGROUND = '#FAFCFE';
export const BUTTON_BORDER = '#3A85B3';
export const BUTTON_BACKGROUND_SECONDARY = '#FFF';
export const BORDER_COLOR = '#E3E5E7';
export const TEXT_COLOR = '#243746';
export const TEXT_CLICKABLE_COLOR = '#3A85B3';

export default {
  HEADER_BACKGROUND,
  PAGE_BACKGROUND,
  BORDER_COLOR,
  TEXT_COLOR,
  BUTTON_BORDER,
  BUTTON_BACKGROUND_SECONDARY,
  TEXT_CLICKABLE_COLOR
};
