require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

use_frameworks!
config = use_native_modules!
use_react_native!(
  :path => config[:reactNativePath],
  # to enable hermes on iOS, change `false` to `true` and then install pods
  :hermes_enabled => false
)

def pods()
  pod 'ReactCommon/turbomodule/samples', :path => '../node_modules/react-native/ReactCommon'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  
  # Additional Pods which aren't included in the default Podfile
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  use_native_modules!
end

target 'McProCoSys' do
  project 'McProCoSys'
  pods()
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
    end
  end
end

